name: Sync src/pages from dev to main

permissions:
  contents: write

on:
  push:
    branches:
      - dev

jobs:
  sync-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Git
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Checkout main branch
        run: git checkout main

      - name: Sync pages, components and styles
        run: |
          git checkout dev -- src/pages src/media src/styles.css src/components/Music.tsx src/components/Overlay.tsx src/components/Slider.tsx src/components/Window.tsx
          git add src/pages src/media src/styles.css  src/components/Music.tsx src/components/Overlay.tsx src/components/Slider.tsx src/components/Window.tsx
          git commit -m "Sync src/pages, src/components, src/media and src/styles.css from dev branch" || echo "No changes to commit"

      - name: Push changes to main
        run: git push origin main
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
